PROJECT = converte_lhe
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

LOCAL_DEPS = inets ssl

DEPS = cowboy jsx
dep_cowboy_commit = 2.11.0

REL_DEPS += relx

DEP_PLUGINS = cowboy

include erlang.mk
