name: Erlang CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-22.04

    container:
      image: erlang:24

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: make Makefile
    - name: Run tests
      run: make tests
